### ISSUE TITLE
全部揃ったときにシャッフルさせないようにしてほしい

### ISSUE THREAD

**Issue by geckotang** [oti/tkg-slot#13]
画像を全部そろえたときに、うっかりクリックしてしまい台無しになることがあります。
そろったときは、そろったエフェクトやダイアログを出して押せないようにするとかそういった何かがあるといいかなと思いました。

ちゃんと見てればいいのでは？というのであれば確かにそうだなという感じでもあります。

**Comment by oti** [comment]
v2 ではTKG写真それぞれをクリックするたびにシャッフルが始まっていましたが、v3 ではストップ専用のボタンを配置し、さらに押した直後に disabled になるようにしました

これで「揃ったのにクリックしてしまい、シャッフルがまた始まってしまった」ということは起きないかと思います。
