### ISSUE TITLE
何かしらでポイントが溜まってそれを消費して揃えやすくする機能がほしい

### ISSUE THREAD

**Issue by geckotang** [oti/tkg-slot#14]
試行回数やツイート、デイリーなどに応じてptがたまり、そのptを消費してスロットが揃いやすくする機能はどうでしょうか。例えば

- スロットが遅くなる
- スロットの画像枚数が減る
- 特定の画像を除去できる

といった機能です。

そして、ptを消費して揃えた際は、ツイートする文面にその旨が書いてあると、普通に揃えた人との差別化ができてよいのかなとも思います。

**Comment by oti** [comment]
難易度を3段階くらいで変更する機能は載せようと思ってます。

**Comment by geckotang** [comment]
:yosasou:

**Comment by oti** [comment]
ポイント制はやらなくていいかな〜と思いました。

イージーモードと目押しモードを実装したので、スロットを揃えやすいオプションは用意できたことにします。
